# Generated by Django 3.2.3 on 2021-05-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210530_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
    ]
