# Generated by Django 3.2.3 on 2021-05-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210530_1803'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_object',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_object'),
        ),
    ]
