# Generated by Django 3.2.3 on 2021-05-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_follow_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_object',
        ),
    ]
