# Generated by Django 3.2.3 on 2021-06-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210530_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_object'),
        ),
    ]
